import turtle
wn = turtle.Screen()
player = turtle.Turtle()
player.shape("turtle")
player.forward(100)
player.left(90)
player.forward(50)
player.left(90)
player.forward(100)
player.left(90)
player.forward(50)
player.left(90)
turtle.mainloop()
